import Link from "next/link";
const weeks=[
 ["Week 1","Listening with presence","Establish the difference between hearing and disciplined listening. Notice assumptions, urgency, internal reaction, and the responsibility carried by interpretation."],
 ["Week 2","Meaning, clarity, and context","Practice careful interpretation, clarification, and reflection while recognizing how context and noise can interfere with what is heard."],
 ["Week 3","From understanding to appropriate support","Explore goals, communication differences, confidence, commitment, compassion, boundaries, and intentional response without turning LISTEN into a script."],
 ["Implementation","Real-world application","Use THE LISTEN MODEL™ in actual conversations, document reflections, and complete a closing assessment and structured feedback experience."]
];
export default function FoundingPilotPage(){return <><section className="pageHero pilotHero"><div className="shell narrow"><p className="eyebrow">FOUNDING PILOT</p><h1>Learn it. Practice it. Use it where listening matters.</h1><p className="heroLead">An early guided learning experience for participants who want to practice THE LISTEN MODEL™ in real conversations while helping shape the program through structured feedback.</p><div className="buttonRow"><Link href="/founding-pilot/register" className="button primary">Register for the Pilot</Link><Link href="/model" className="button secondary">Review the Model</Link></div></div></section>
<section className="section"><div className="shell"><div className="pilotIntro"><div><p className="eyebrow">THE EXPERIENCE</p><h2>Three weeks of guided learning. One implementation period.</h2></div><p className="sectionLead">The pilot introduces the public L.I.S.T.E.N. framework and foundational listening practices without reproducing advanced practitioner, certification, or licensing methods.</p></div><div className="pilotTimeline">{weeks.map(([label,title,text],i)=><article className="pilotWeek" key={label}><span className="number">{String(i+1).padStart(2,"0")}</span><p className="eyebrow">{label}</p><h3>{title}</h3><p>{text}</p></article>)}</div><div className="pilotActions"><Link href="/assessment" className="button secondary">Take the Self-Assessment</Link><Link href="/learn/presence-interpretation" className="button secondary">Preview Foundational Module</Link></div></div></section>
<section className="section splitSection"><div className="shell twoCol"><div><p className="eyebrow">PARTICIPANT JOURNEY</p><h2>Practice before, during, and after the conversation.</h2></div><div className="listCard"><ul className="checkList"><li>Beginning listening reflection and learning goals</li><li>Introduction to L.I.S.T.E.N. and its ethical orientation</li><li>Foundational practice in presence, interpretation, clarification, reflection, and response</li><li>Real-world listening assignments</li><li>Reflection and implementation notes</li><li>Closing assessment, feedback, and next-step plan</li></ul></div></div></section>
<section className="ctaBand"><div className="shell ctaInner"><div><p className="eyebrow light">FOUNDING PARTICIPANTS</p><h2>Help put intentional listening into practice.</h2><p>Individuals, teams, mentors, educators, and leaders can request information about participating in an early pilot.</p></div><Link href="/founding-pilot/register" className="button lightButton">Register for the Pilot</Link></div></section></>}
